// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xrsa_toplevel.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XRsa_toplevel_CfgInitialize(XRsa_toplevel *InstancePtr, XRsa_toplevel_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XRsa_toplevel_Start(XRsa_toplevel *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_AP_CTRL) & 0x80;
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XRsa_toplevel_IsDone(XRsa_toplevel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XRsa_toplevel_IsIdle(XRsa_toplevel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XRsa_toplevel_IsReady(XRsa_toplevel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XRsa_toplevel_EnableAutoRestart(XRsa_toplevel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XRsa_toplevel_DisableAutoRestart(XRsa_toplevel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_AP_CTRL, 0);
}

void XRsa_toplevel_Set_inData_V(XRsa_toplevel *InstancePtr, XRsa_toplevel_Indata_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 0, Data.word_0);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 4, Data.word_1);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 8, Data.word_2);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 12, Data.word_3);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 16, Data.word_4);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 20, Data.word_5);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 24, Data.word_6);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 28, Data.word_7);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 32, Data.word_8);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 36, Data.word_9);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 40, Data.word_10);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 44, Data.word_11);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 48, Data.word_12);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 52, Data.word_13);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 56, Data.word_14);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 60, Data.word_15);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 64, Data.word_16);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 68, Data.word_17);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 72, Data.word_18);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 76, Data.word_19);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 80, Data.word_20);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 84, Data.word_21);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 88, Data.word_22);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 92, Data.word_23);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 96, Data.word_24);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 100, Data.word_25);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 104, Data.word_26);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 108, Data.word_27);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 112, Data.word_28);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 116, Data.word_29);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 120, Data.word_30);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 124, Data.word_31);
}

XRsa_toplevel_Indata_v XRsa_toplevel_Get_inData_V(XRsa_toplevel *InstancePtr) {
    XRsa_toplevel_Indata_v Data;

    Data.word_0 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 0);
    Data.word_1 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 4);
    Data.word_2 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 8);
    Data.word_3 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 12);
    Data.word_4 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 16);
    Data.word_5 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 20);
    Data.word_6 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 24);
    Data.word_7 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 28);
    Data.word_8 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 32);
    Data.word_9 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 36);
    Data.word_10 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 40);
    Data.word_11 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 44);
    Data.word_12 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 48);
    Data.word_13 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 52);
    Data.word_14 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 56);
    Data.word_15 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 60);
    Data.word_16 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 64);
    Data.word_17 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 68);
    Data.word_18 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 72);
    Data.word_19 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 76);
    Data.word_20 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 80);
    Data.word_21 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 84);
    Data.word_22 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 88);
    Data.word_23 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 92);
    Data.word_24 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 96);
    Data.word_25 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 100);
    Data.word_26 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 104);
    Data.word_27 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 108);
    Data.word_28 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 112);
    Data.word_29 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 116);
    Data.word_30 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 120);
    Data.word_31 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_INDATA_V_DATA + 124);
    return Data;
}

XRsa_toplevel_Outdata_v XRsa_toplevel_Get_outData_V(XRsa_toplevel *InstancePtr) {
    XRsa_toplevel_Outdata_v Data;

    Data.word_0 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 0);
    Data.word_1 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 4);
    Data.word_2 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 8);
    Data.word_3 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 12);
    Data.word_4 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 16);
    Data.word_5 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 20);
    Data.word_6 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 24);
    Data.word_7 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 28);
    Data.word_8 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 32);
    Data.word_9 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 36);
    Data.word_10 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 40);
    Data.word_11 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 44);
    Data.word_12 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 48);
    Data.word_13 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 52);
    Data.word_14 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 56);
    Data.word_15 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 60);
    Data.word_16 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 64);
    Data.word_17 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 68);
    Data.word_18 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 72);
    Data.word_19 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 76);
    Data.word_20 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 80);
    Data.word_21 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 84);
    Data.word_22 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 88);
    Data.word_23 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 92);
    Data.word_24 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 96);
    Data.word_25 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 100);
    Data.word_26 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 104);
    Data.word_27 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 108);
    Data.word_28 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 112);
    Data.word_29 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 116);
    Data.word_30 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 120);
    Data.word_31 = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_DATA + 124);
    return Data;
}

u32 XRsa_toplevel_Get_outData_V_vld(XRsa_toplevel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_OUTDATA_V_CTRL);
    return Data & 0x1;
}

void XRsa_toplevel_InterruptGlobalEnable(XRsa_toplevel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_GIE, 1);
}

void XRsa_toplevel_InterruptGlobalDisable(XRsa_toplevel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_GIE, 0);
}

void XRsa_toplevel_InterruptEnable(XRsa_toplevel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_IER);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_IER, Register | Mask);
}

void XRsa_toplevel_InterruptDisable(XRsa_toplevel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_IER);
    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_IER, Register & (~Mask));
}

void XRsa_toplevel_InterruptClear(XRsa_toplevel *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRsa_toplevel_WriteReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_ISR, Mask);
}

u32 XRsa_toplevel_InterruptGetEnabled(XRsa_toplevel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_IER);
}

u32 XRsa_toplevel_InterruptGetStatus(XRsa_toplevel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XRsa_toplevel_ReadReg(InstancePtr->Axilites_BaseAddress, XRSA_TOPLEVEL_AXILITES_ADDR_ISR);
}

