// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xrsa_toplevel.h"

extern XRsa_toplevel_Config XRsa_toplevel_ConfigTable[];

XRsa_toplevel_Config *XRsa_toplevel_LookupConfig(u16 DeviceId) {
	XRsa_toplevel_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XRSA_TOPLEVEL_NUM_INSTANCES; Index++) {
		if (XRsa_toplevel_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XRsa_toplevel_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XRsa_toplevel_Initialize(XRsa_toplevel *InstancePtr, u16 DeviceId) {
	XRsa_toplevel_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XRsa_toplevel_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XRsa_toplevel_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

