// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_rsaModExp (
ap_uint<2048> M,
ap_uint<2048> e,
ap_uint<2048> n,
ap_uint<2048>* out);
