// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void rsaModExp (
ap_uint<1024> M,
ap_uint<1024> e,
ap_uint<1024> n,
ap_uint<1024>* out);
