// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "inData_V"
#define AUTOTB_TVIN_inData_V  "../tv/cdatafile/c.rsa_toplevel.autotvin_inData_V.dat"
// wrapc file define: "outData_V"
#define AUTOTB_TVOUT_outData_V  "../tv/cdatafile/c.rsa_toplevel.autotvout_outData_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "outData_V"
#define AUTOTB_TVOUT_PC_outData_V  "../tv/rtldatafile/rtl.rsa_toplevel.autotvout_outData_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			inData_V_depth = 0;
			outData_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{inData_V " << inData_V_depth << "}\n";
			total_list << "{outData_V " << outData_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int inData_V_depth;
		int outData_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define rsa_toplevel AESL_ORIG_DUT_rsa_toplevel
extern void rsa_toplevel (
ap_uint<1024>* inData,
ap_uint<1024>* outData);
#undef rsa_toplevel

void rsa_toplevel (
ap_uint<1024>* inData,
ap_uint<1024>* outData)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "outData_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_outData_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_outData_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_outData_V, AESL_token); // data

			sc_bv<1024> *outData_V_pc_buffer = new sc_bv<1024>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'outData_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'outData_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					outData_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_outData_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_outData_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: outData_V
				{
					// bitslice(1023, 0)
					// {
						// celement: outData.V(1023, 0)
						// {
							sc_lv<1024>* outData_V_lv0_0_0_1 = new sc_lv<1024>[1];
						// }
					// }

					// bitslice(1023, 0)
					{
						int hls_map_index = 0;
						// celement: outData.V(1023, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(outData[0]) != NULL) // check the null address if the c port is array or others
								{
									outData_V_lv0_0_0_1[hls_map_index++].range(1023, 0) = sc_bv<1024>(outData_V_pc_buffer[hls_map_index].range(1023, 0));
								}
							}
						}
					}

					// bitslice(1023, 0)
					{
						int hls_map_index = 0;
						// celement: outData.V(1023, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : outData[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : outData[0]
								// output_left_conversion : outData[i_0]
								// output_type_conversion : (outData_V_lv0_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
								if (&(outData[0]) != NULL) // check the null address if the c port is array or others
								{
									outData[i_0] = (outData_V_lv0_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] outData_V_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "inData_V"
		char* tvin_inData_V = new char[261];
		aesl_fh.touch(AUTOTB_TVIN_inData_V);

		// "outData_V"
		char* tvout_outData_V = new char[261];
		aesl_fh.touch(AUTOTB_TVOUT_outData_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_inData_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_inData_V, tvin_inData_V);

		sc_bv<1024>* inData_V_tvin_wrapc_buffer = new sc_bv<1024>[1];

		// RTL Name: inData_V
		{
			// bitslice(1023, 0)
			{
				int hls_map_index = 0;
				// celement: inData.V(1023, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : inData[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : inData[0]
						// regulate_c_name       : inData_V
						// input_type_conversion : (inData[i_0]).to_string(2).c_str()
						if (&(inData[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1024> inData_V_tmp_mem;
							inData_V_tmp_mem = (inData[i_0]).to_string(2).c_str();
							inData_V_tvin_wrapc_buffer[hls_map_index++].range(1023, 0) = inData_V_tmp_mem.range(1023, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_inData_V, "%s\n", (inData_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_inData_V, tvin_inData_V);
		}

		tcl_file.set_num(1, &tcl_file.inData_V_depth);
		sprintf(tvin_inData_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_inData_V, tvin_inData_V);

		// release memory allocation
		delete [] inData_V_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		AESL_ORIG_DUT_rsa_toplevel(inData, outData);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_outData_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_outData_V, tvout_outData_V);

		sc_bv<1024>* outData_V_tvout_wrapc_buffer = new sc_bv<1024>[1];

		// RTL Name: outData_V
		{
			// bitslice(1023, 0)
			{
				int hls_map_index = 0;
				// celement: outData.V(1023, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : outData[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : outData[0]
						// regulate_c_name       : outData_V
						// input_type_conversion : (outData[i_0]).to_string(2).c_str()
						if (&(outData[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1024> outData_V_tmp_mem;
							outData_V_tmp_mem = (outData[i_0]).to_string(2).c_str();
							outData_V_tvout_wrapc_buffer[hls_map_index++].range(1023, 0) = outData_V_tmp_mem.range(1023, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_outData_V, "%s\n", (outData_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_outData_V, tvout_outData_V);
		}

		tcl_file.set_num(1, &tcl_file.outData_V_depth);
		sprintf(tvout_outData_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_outData_V, tvout_outData_V);

		// release memory allocation
		delete [] outData_V_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "inData_V"
		delete [] tvin_inData_V;
		// release memory allocation: "outData_V"
		delete [] tvout_outData_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

